@startuml

title Consumo de tateriales del almacen

": Construccion" -> ": Almacen": construir(consumos)
loop "c" en (consumos)
    loop "a" en (almacen)
        ": Almacen" -> "a: Material": reducirCantidadEquivalenteA(m)
    end loop
end loop


@enduml