@startuml

title Caso 1

create "c: Cemento"
": TestCase" -> "c: Cemento": Cemento(100)

create "n: Caño"
": TestCase" -> "n: Caño": Caño(50)
 
create "p: Pintura"
": TestCase" -> "p: Pintura": Pintura(2500)
 
create "a: Almacen"
": TestCase" -> "a: Almacen": Almacen(c, n, p)

create ": Casa"
": TestCase" -> ": Casa": Casa(5 /* ambientes */)

": Casa" -> ": Casa": iniciarRequisitosAmbiente()
activate ": Casa"

create "cA: Cemento"
": Casa" -> "cA: Cemento": Cemento(10)

create "nA: Caño"
": Casa" -> "nA: Caño": Caño(100)

create "pA: Pintura"
": Casa" -> "pA: Pintura": Pintura(500)

deactivate ": Casa"

": Casa" -> ": Casa": iniciarRequisitosBase()
activate ": Casa"

create "cB: Cemento"
": Casa" -> "cB: Cemento": Cemento(50)

deactivate ": Casa"
": TestCase" -> ": Casa": construirCon(a)
": Casa" -> "a: Almacen": construir(base)

loop para cada ambiente
": Casa" -> "a: Almacen": construir(ambiente)
end

": Casa" --> ": TestCase": [Almacen(new Cemento(0), new Caño(0), new Pintura(0))]
@enduml