@startuml

title Caso 2

create "c: Cemento"
": TestCase" -> "c: Cemento": Cemento(800)

create "n: Caño"
": TestCase" -> "n: Caño": Caño(900)
 
create "p: Pintura"
": TestCase" -> "p: Pintura": Pintura(2900)
 
create "a: Almacen"
": TestCase" -> "a: Almacen": Almacen(c, n, p)

create ": Edificio"
": TestCase" -> ": Edificio": Edificio(5 /* nro pisos */)

": Edificio" -> ": Edificio": iniciarRequisitosBase()
activate ": Edificio"

create "cE: Cemento"
": Edificio" -> "cE: Cemento": Cemento(100)

create "nE: Caño"
": Edificio" -> "nE: Caño": Caño(100)

create "pE: Pintura"
": Edificio" -> "pE: Pintura": Pintura(100)

deactivate ": Edificio"

": TestCase" -> ": Edificio": construirCon(a)
": Edificio" -> ": Edificio": consumirBase(a)
": Edificio" -> "a: Almacen": consumir(base)
": Edificio" -> ": Edificio": consumirVivienda(a)
activate ": Edificio"
create "eC : Casa"
": Edificio" -> "eC : Casa": Casa(...)

": Edificio" -> "eC : Casa": construirCon(a)
note right
    Misma secuencia "Caso 1"
end note
return

deactivate ": Edificio"

loop para cada planta
": Edificio" -> ": Edificio": consumirPlanta(a, nroPlanta)
activate ": Edificio"
": Edificio" -> "a: Almacen": consumir(materialesPlanta)
deactivate ": Edificio"

end

": Edificio" --> ": TestCase":  [Almacen(new Cemento(0), new Caño(0), new Pintura(0))]
@enduml